public with sharing class CustomLeaseIndexationConstants {
    public static final String LEASE_HOUSING_SECTOR_PRIVATE_SECTOR = 'Private Sector';
    public static final String LEASE_HOUSING_SECTOR_MID_RENTAL_SECTOR = 'Mid-Rental Sector';
    public static final String LEASE_HOUSING_SECTOR_SOCIAL_SECTOR = 'Social Sector';
    public static final String LEASE_SECTOR_TYPE_RESIDENTIAL = 'Residential';
    public static final String INVOICE_FREQUENCY_ONLY_ONCE = 'Only Once';
}
